### ISSUE TITLE
Deprecated API key warning and failure to purge

### ISSUE THREAD

**Issue by noahcostello** [nystudio107/craft3-imageoptimize#273]
### Describe the bug
Replacing files results in a depreciation warning about IMGIX security key when image optimize tries to purge the old asset.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Asset volume with an image optimize field applied"
2. Click on "Select and individual asset and click the replace button, then replace it with a new file with the same name as the file being replaced"
3. See error message "Depreciation warning is output in craft: `You are using a deprecated API key. Obtain a new API key to use the purging API. More info: https://blog.imgix.com/2020/10/16/api-deprecation"`

### Expected behaviour
Expecting the cached image to be purged from IMGIX and the new image to load on site, but the old image remains as purge fails.

The API key is set via a .env variable.  I've tried creating a brand new API key and still no luck.

### Versions
- Plugin version: 1.6.30
- Craft version: Craft Pro 3.6.12

**Comment by khalwat** [comment]
There was an update to change it to use the latest API key APIs in:

https://github.com/nystudio107/craft-imageoptimize-imgix/commit/a368731fd43e2c676da9d25bd882a77897227b2d

What version of `nystudio107/craft-imageoptimize-imgix` do you have installed?

What does your API key look like?

**Comment by noahcostello** [comment]
Version 1.2.1

It might have popped up around the time of that update, we weren't in production yet, so may not have noticed.  

The original key we were using seemed to be in the new format, but I generated a new one anyway which looks like this. 

ak_2a02b31a3e839428b2750e2561e0abfda8639aca3a7827575684fa899dXXXXXX (swapped the last 6 digits with X)

**Comment by noahcostello** [comment]
It seems like we have the settings right and the API key is the new format. Are there any other debugging steps you recommend taking to try and get to the bottom of it?

**Comment by khalwat** [comment]
No, if you have double-checked everything, I will attempt to reproduce it here locally.

**Comment by noahcostello** [comment]
Yeah, I'm not sure what else to try. New API keys has not solved it and all the settings seem right. Thanks.

**Comment by chadwells** [comment]
Chiming in to mention we also have been having this exact issue, running latest version of the plugin (and nystudio107/craft-imageoptimize-imgix is installed @ version 1.2.2 according to my composer.lock). Willing to help solve!

**Comment by khalwat** [comment]
Will get it reproduced locally and then fixed

**Comment by transf3r** [comment]
I'm having the same issue as @chadwells . Deprecated API key warning. I've regenerate the IMGIX api key and replaced env variable. Image transforms are not being updated within Craft.  Imageoptimise plugin v 1.6.34 / craft-imageoptimize-imgix v1.2.2

**Comment by khalwat** [comment]
Addressed in ImageOptimize 1.6.36 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.36

**Comment by chadwells** [comment]
This deprecation error message still appears when attempting to purge via asset replacement. Currently on craft-imageoptimize v1.6.41

**Comment by ishetnogferre** [comment]
We're also still getting the deprecation error and the image not purged.

Are using:
- Craft CMS: 4.2.3
- ImageOptimize 4.0.2
- ApiKey in format: ak_bcac95XXX3f0c99XXb9dXXXb2e4623f6f7XXXXXXXX8825050c7f13c584d3XXXX
