### ISSUE TITLE
Configuration troubles

### ISSUE THREAD

**Issue by acespace90** [nystudio107/craft3-imageoptimize#310]
### Question
Hi, I'm struggling with configuration. I've just installed the plugin in its Trial version. I'm following this guide https://nystudio107.com/docs/image-optimize/using.html but when I create an OptimizedImages I have no possibilities to add to an Asset Volume despite I have it. 

Moreover I can't delete or add variants. Can you help me?

<img width="2005" alt="Screenshot 2022-01-17 at 13 21 15" src="https://user-images.githubusercontent.com/12846842/149768600-32753b15-66ce-478f-9319-5c2acecb54e4.png">

**Comment by khalwat** [comment]
What is happening is the JavaScript to create the new field settings is being executed before the script that implements `Craft.OptimizedImagesInput()` has been run.

I'm investigating.

**Comment by khalwat** [comment]
Alright, so this was a fun one. Essentially what was happening is the JavaScript to create the ImageOptimize field settings was firing before the JavaScript module was loaded, causing an error in the JavaScript console, and nothing to appear on the page.

To fix this, I added an `onload` event fired by the Vite-generated script here: 

`craft-plugin-vite`: https://github.com/nystudio107/craft-plugin-vite/commit/bd1ef7639d7f9188f74c866a836c38cee6e68dd6#diff-7822397b9bf7419a9ceef3efa170cb314b92846a18348b54a8c68760f0830d67R131

...which allows me to add a listener that gets notified when the script is loaded, after which I can execute the necessary JavaScript:

`craft-imageoptimize`: https://github.com/nystudio107/craft-imageoptimize/commit/4b06c3a318f51123e87ee68e046841518717031a#diff-10becf48966b4b8d388ebb845637b040fcb6b0944f096964543566fd2003741cR328

Documented here: https://nystudio107.com/docs/vite/#script-onload-events

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.41”,
```
Then do a `composer clear-cache && composer update`

lmk how you go

**Comment by khalwat** [comment]
I pushed a fix for the above that should fix an issue where the event was firing before the listener was even installed, in some cases (it’s async, so you never know)

Doing this again should pull down the latest:

```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.41”,
```
Then do a `composer clear-cache && composer update`

lmk how you go

**Comment by khalwat** [comment]
Released as 1.6.41 -> https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.41

**Comment by acespace90** [comment]
Hi thank you so much for the investigation, but I'm still having the same problem. I can't add the field to an Asset volume.

I ran `composer clear-cache && composer update` and updated to 1.6.41

This is what I have in my `composer.json`

```
"nystudio107/craft-imageoptimize": "1.6.41"
```

<img width="2545" alt="Screenshot 2022-01-18 at 11 04 26" src="https://user-images.githubusercontent.com/12846842/149916209-e92dc853-5bdf-45b4-b9eb-5e895e3b8312.png">

**Comment by khalwat** [comment]
This screenshot doesn't really show me anything -- can you scroll down and how me the problem area?

**Comment by acespace90** [comment]
Sure. The point is that I can't see these fields (image taken from the [doc](https://nystudio107.com/docs/image-optimize/using.html#using-the-optimized-images-field))

![image-optimize-field-volumes d23823f9](https://user-images.githubusercontent.com/12846842/149954367-b78b2130-67b3-40df-8096-de7181ce1bbf.png)

This is the entire page screenshot.

![screencapture-localhost-18080-admin-settings-fields-new-2022-01-18-15_15_31](https://user-images.githubusercontent.com/12846842/149954474-921f1535-1741-4c6b-b00c-3f4251144af5.jpeg)

And of course when I go to an Entry this is what I have.

<img width="662" alt="Screenshot 2022-01-18 at 15 19 51" src="https://user-images.githubusercontent.com/12846842/149954775-c6830638-88c3-4303-a214-482ef6ce2b58.png">

By the way, am I the one that is having this problem?

**Comment by khalwat** [comment]
Okay, so that screenshot looks right to me. I think I'm not clearly understanding the problem you've having?

If you create the field, and then go to Settings -> Assets are you unable to drag the Optimized Images field to an asset volume's field layout?

**Comment by acespace90** [comment]
Okay, I'm probably doing something wrong. I'm not sure I understand then how to configure the field correctly.

What I did was create the OptimizedImages field into Settings ->Fields , but I can't figure out how to associate it to an asset volume.
Can you please explain to me step by step?

At some point I expect to do this as the doc says. But how?

![image-optimize-field-volumes d23823f9](https://user-images.githubusercontent.com/12846842/149956935-03ed5e00-dbaf-4fe4-8857-09a4d2949929.png)

**Comment by khalwat** [comment]
After you have created the Optimized Images field, go to:

Settings -> Assets then click on an Asset Volume, and then scroll down to add the field to the Asset Volume's field layout:

<img width="1560" alt="Screen Shot 2022-01-18 at 9 35 49 AM" src="https://user-images.githubusercontent.com/7570798/149957789-8f2159a2-ed3c-4437-bf84-f50637b6d869.png">

**Comment by acespace90** [comment]
Ok thank you, now I understand and I see all the variants of an image. 

How do then I upload image in an Entry on Craft?

**Comment by khalwat** [comment]
You just upload it as you normally would, and if it is in asset volume that has an Optimized Images field added to the field layout, it'll automatically generate all of the image variants for that image.

**Comment by acespace90** [comment]
Right!
Thank you so much for your patience and sorry if I wasted your time

**Comment by khalwat** [comment]
Not at all, that's what I'm here for! No worries.
