### ISSUE TITLE
srcsetMaxWidth returns incorrect image sizes

### ISSUE THREAD

**Issue by almeric** [nystudio107/craft3-imageoptimize#407]
### Describe the bug
`image.optimized.srcsetMaxWidth(576)` returns wrong image sizes. I've narrowed it down to here:

https://github.com/nystudio107/craft-imageoptimize/blob/v5/src/models/OptimizedImage.php#L642-L644

`$set` and `$this->variantSourceWidths` are not ordered the same. `$set` starts with the smallest size, while `﻿﻿﻿﻿﻿variantSourceWidths` starts with the largest size. Therefore you can't slice using the index.

Example (urls omitted):

`$set`:
```php
{
  "320": "url",
  "480": "url",
  "576": "url",
  "768": "url",
  "1280": "url",
  "1440": "url",
  "1920": "url",
  "2048": "url"
}
``` 

`﻿variantSourceWidths`:
```php
[
  "2048",
  "1920",
  "1440",
  "1280",
  "768",
  "576",
  "480",
  "320"
]
```

### To reproduce
Steps to reproduce the behaviour:

```twig
   {{ image.optimized.srcsetMaxWidth(576) }}
```

Returns images with sizes 1440, 1920, 2048

### Expected behaviour
Images with sizes 320, 480, 576

### Versions
- Plugin version: 5.0.1
- Craft version: 5.1.9

**Comment by almeric** [comment]
@khalwat any chance you can take a look at this?

**Comment by khalwat** [comment]
Yessir, I am away at the moment, but I return on Saturday. It's on my list!

**Comment by khalwat** [comment]
Addressed in the above commits

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.55”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v5 as 5.0.2”,
```
Then do a `composer clear-cache && composer update`

**Comment by almeric** [comment]
Thanks @khalwat! Unfortunately it's not completely fixed:

Using `ksort` for `variantSourceWidths` won't work as it's already sorted by key, you'll have to sort by value I guess?

See debug info:

![Screenshot 2024-06-17 at 13 24 51](https://github.com/nystudio107/craft-imageoptimize/assets/1922968/0ab9ad10-13ef-4114-9dbc-0c3f22d06cb5)

`ksort` won't have any effect here.

**Comment by khalwat** [comment]
My bad... Addressed it in the `dev` branches, do this again to test it. Here's the commit:

https://github.com/nystudio107/craft-imageoptimize/commit/db1c1fe99c60e438fd0c8b5fe6eff81c478e9ca7

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.55”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v5 as 5.0.2”,
```
Then do a `composer clear-cache && composer update`

**Comment by almeric** [comment]
Thanks! All is working as expected now!
