### ISSUE TITLE
First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by sjenset** [nystudio107/craft3-imageoptimize#50]
Hi.

Just installed the plugin on Craft3-RC10.1 and hooked it up to Imgix. In the backend, the image-variations show up just fine when editing an asset. However, in the frontend, I get the error listed in the subject.

My template-code is:

    {% if section.images|length %}
      <div class="section__images">
        {% for image in section.images.all %}
          {% set optimizedImages = image.variations %}
        {% endfor %}
      </div>
    {% endif %}

Obviously, I have tried with the various methods of displaying the images as per [the examples](https://github.com/nystudio107/craft-imageoptimize) - but as you can see the error occurs *before* I attempt to display them.

The error stems from `/vendor/nystudio107/craft-imageoptimize/src/imagetransforms/ImgixImageTransform.php` line 88, which reads `if (property_exists($transform, 'interlace')) {`

Let me know if you need any screenshots or details about my various settings etc :)

**Comment by khalwat** [comment]
That's really strange; it's essentially saying that the transform that's being passed in isn't an object. Can you give me the full stack trace from the error so I can see what the call chain is?

**Comment by khalwat** [comment]
I think I know what's going on here... you're probably using regular Craft CMS transforms in your templates as well, yes?

**Comment by khalwat** [comment]
This should be fixed in 1.4.17; let me know if it works for you:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.17

**Comment by sjenset** [comment]
Yeah, there were probably calls to regular Craft-transforms (edited note: I was using transforms defined as objects in my Twig-templates; there were no transforms defined through the Craft back-end) "here and there" in my source-code still; as I said I had just installed the plugin to give it a go.

Will test with v1.4.17 during the day and keep you updated :)

**Comment by sjenset** [comment]
Okay - so the issue originally reported did indeed go away with v1.4.17 - however, I am still seeing errors.

This time they occur on line 99 of `/vendor/nystudio107/craft-imageoptimize/src/imagetransforms/ImgixImageTransform.php`: `$heightScale = $asset->getHeight() / $transform->height;`

**Comment by sjenset** [comment]
````
2018-02-19 09:24:34 [192.168.168.1][1][44fndr5tg1kjubrje2tdruei47][trace][nystudio107\imageoptimize\{closure}] Assets::EVENT_GET_ASSET_URL
2018-02-19 09:24:34 [192.168.168.1][1][44fndr5tg1kjubrje2tdruei47][error][yii\base\ErrorException:2] yii\base\ErrorException: Division by zero in /vendor/nystudio107/craft-imageoptimize/src/imagetransforms/ImgixImageTransform.php:99

Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'Division by zer...', '/var/www/istad....', 99)
#1 /vendor/nystudio107/craft-imageoptimize/src/imagetransforms/ImgixImageTransform.php(99): craft\web\ErrorHandler->handleError(2, 'Division by zer...', '/var/www/istad....', 99, Array)
#2 /vendor/nystudio107/craft-imageoptimize/src/services/Optimize.php(91): nystudio107\imageoptimize\imagetransforms\ImgixImageTransform::getTransformUrl(Object(craft\elements\Asset), Object(craft\models\AssetTransform), Array)
#3 /vendor/nystudio107/craft-imageoptimize/src/ImageOptimize.php(214): nystudio107\imageoptimize\services\Optimize->handleGetAssetUrlEvent(Object(craft\events\GetAssetUrlEvent))
#4 [internal function]: nystudio107\imageoptimize\ImageOptimize->nystudio107\imageoptimize\{closure}(Object(craft\events\GetAssetUrlEvent))
#5 /vendor/yiisoft/yii2/base/Event.php(221): call_user_func(Object(Closure), Object(craft\events\GetAssetUrlEvent))
#6 /vendor/yiisoft/yii2/base/Component.php(565): yii\base\Event::trigger('craft\\services\\...', 'getAssetUrl', Object(craft\events\GetAssetUrlEvent))
#7 /vendor/craftcms/cms/src/services/Assets.php(564): yii\base\Component->trigger('getAssetUrl', Object(craft\events\GetAssetUrlEvent))
#8 /vendor/craftcms/cms/src/elements/Asset.php(721): craft\services\Assets->getAssetUrl(Object(craft\elements\Asset), Array)
#9 /vendor/twig/twig/lib/Twig/Extension/Core.php(1595): craft\elements\Asset->getUrl(Array)
#10 /vendor/craftcms/cms/src/helpers/Template.php(76): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Asset), 'url', Array, 'method', false, false)
#11 /storage/runtime/compiled_templates/13/13587eeb8fbe5bd64f657d53c8796016435f33d3b3e427a5db4d1a46e4cc98bb.php(45): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Asset), 'url', Array, 'method')
#12 /vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_daa34e4594d4466d97843dab5cf6ff9e7ef6f7a153a3ccf3e802c71719370851->doDisplay(Array, Array)
#13 /vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#14 /vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#15 /vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#16 /storage/runtime/compiled_templates/b3/b3ac72933716ffe66369083db0ba5da0060ef07dcf554c74a709cdaaf09bd06c.php(58): craft\web\twig\Template->display(Array)
#17 /vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_c27fb545c7eeff88e5c8ee601b27b6f087ff973ca7d4a1d78b879d2dab4754da->doDisplay(Array, Array)
#18 /vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#19 /vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#20 /vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#21 /storage/runtime/compiled_templates/c0/c051089a589f43c48cc492053934e600608ea5be886e63cb42ed619c08539eb3.php(45): craft\web\twig\Template->display(Array)
#22 /vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_8c37fefa85e42df1a341cd3260999dccb83696a05343dfabb694585a3be29b03->block_main(Array, Array)
#23 /storage/runtime/compiled_templates/57/575c8db238932860fef9b11705b5f942e7a6eb7b4bbab8c8c1c5b4b17b93851a.php(166): Twig_Template->displayBlock('main', Array, Array)
#24 /vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_42487e86c69d05b0c91aee233620d428f7e42f71fb1c8d330b7cd52607db8fbe->doDisplay(Array, Array)
#25 /vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#26 /vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#28 /storage/runtime/compiled_templates/c0/c051089a589f43c48cc492053934e600608ea5be886e63cb42ed619c08539eb3.php(26): craft\web\twig\Template->display(Array, Array)
#29 /vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_8c37fefa85e42df1a341cd3260999dccb83696a05343dfabb694585a3be29b03->doDisplay(Array, Array)
#30 /vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#31 /vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#33 /vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#34 /vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#35 /vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('index', Array)
#36 /vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('index', '[<span class="s...')
#37 /vendor/craftcms/cms/src/web/Controller.php(120): craft\web\View->renderPageTemplate('index', '[<span class="s...')
#38 /vendor/craftcms/cms/src/controllers/TemplatesController.php(79): craft\web\Controller->renderTemplate('index', Array)
#39 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#40 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#42 /vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('render', Array)
#43 /vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#44 /vendor/craftcms/cms/src/web/Application.php(240): yii\base\Module->runAction('templates/rende...', Array)
#45 /vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#46 /vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /var/www/istad.dev/public/jubileum/index.php(30): yii\base\Application->run()
#49 {main}
````

**Comment by khalwat** [comment]
d'oh! Should be fixed in 1.4.18:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.18

Let me know!

**Comment by sjenset** [comment]
That seems to have fixed it, thanks! :)

Now I just need to figure out how to get the various placeholders to adhere to the aspect of the variations :)
